export const advaitaEssentialLevels = [
  "Fundamentos revelados",
  "Exposición clásica",
  "Manuales de discernimiento",
  "Profundización y diálogo",
  "Textos contemplativos y recepción contemporánea",
] as const;

export type AdvaitaEssentialLevel = (typeof advaitaEssentialLevels)[number];

export type AdvaitaEssentialBook = {
  id: string;
  order: number;
  title: string;
  originalTitle?: string;
  author: string;
  date: string;
  level: AdvaitaEssentialLevel;
  purpose: string;
  url: string;
  source: string;
  access: string;
  note?: string;
};

export const advaitaEssentialBooks: readonly AdvaitaEssentialBook[] = [
  {
    id: "principal-upanishads",
    order: 1,
    title: "Upaniṣads principales",
    author: "Tradición védica",
    date: "ca. 700–100 a. C. · estratos y fechas aproximados",
    level: "Fundamentos revelados",
    purpose: "Fuente de la investigación sobre ātman, Brahman, conocimiento y liberación.",
    url: "https://vedicheritage.gov.in/upanishads/",
    source: "Vedic Heritage Portal",
    access: "Textos sánscritos en portal oficial",
  },
  {
    id: "bhagavad-gita-shankara",
    order: 2,
    title: "Bhagavad Gītā con comentario de Śaṅkara",
    originalTitle: "Bhagavadgītā Śāṅkarabhāṣya",
    author: "Tradicionalmente atribuida a Vyāsa · comentario de Śaṅkara",
    date: "Gītā ca. 200 a. C.–200 d. C. · comentario ca. siglo VIII",
    level: "Fundamentos revelados",
    purpose: "Integra acción, preparación, devoción y conocimiento dentro del Prasthānatrayī.",
    url: "https://www.gitasupersite.iitk.ac.in/",
    source: "Gita Supersite · IIT Kanpur",
    access: "Texto, traducciones y comentarios",
  },
  {
    id: "brahma-sutra-bhashya",
    order: 3,
    title: "Brahma Sūtras con comentario de Śaṅkara",
    originalTitle: "Brahmasūtra Śāṅkarabhāṣya",
    author: "Bādarāyaṇa · comentario de Śaṅkara",
    date: "Sūtras ca. 200 a. C.–200 d. C. · comentario ca. siglo VIII",
    level: "Fundamentos revelados",
    purpose: "Organiza y argumenta la lectura no dual de las Upaniṣads.",
    url: "https://www.gitasupersite.iitk.ac.in/bs_home",
    source: "Gita Supersite · IIT Kanpur",
    access: "Texto y comentario académico",
  },
  {
    id: "mandukya-karika",
    order: 4,
    title: "Māṇḍūkya Upaniṣad con Kārikā",
    originalTitle: "Māṇḍūkyopaniṣad Gauḍapādakārikā",
    author: "Tradición upaniṣádica · Gauḍapāda",
    date: "Upaniṣad antigua · Kārikā ca. siglo VI",
    level: "Fundamentos revelados",
    purpose: "Investiga Oṃ, los estados de experiencia, Turīya y la no-originación.",
    url: "https://sanskritdocuments.org/doc_upanishhat/kaarikaa.html",
    source: "Sanskrit Documents",
    access: "Texto sánscrito y transliteración",
  },
  {
    id: "upadesasahasri-essential",
    order: 5,
    title: "Upadeśasāhasrī",
    originalTitle: "Mil enseñanzas",
    author: "Śaṅkara",
    date: "ca. siglo VIII",
    level: "Exposición clásica",
    purpose: "Expone directamente el método de enseñanza no dual en prosa y verso.",
    url: "https://sanskritdocuments.org/doc_z_misc_shankara/US_itran_new.html",
    source: "Sanskrit Documents",
    access: "Texto sánscrito transliterado",
  },
  {
    id: "naishkarmya-siddhi",
    order: 6,
    title: "Naiṣkarmyasiddhi",
    author: "Sureśvara",
    date: "ca. siglo VIII",
    level: "Exposición clásica",
    purpose: "Examina la relación entre acción, renuncia, conocimiento y liberación.",
    url: "https://sanskritdocuments.org/doc_z_misc_major_works/naishk.html",
    source: "Sanskrit Documents",
    access: "Texto sánscrito en línea",
  },
  {
    id: "tattva-bodha-essential",
    order: 7,
    title: "Tattva Bodha",
    originalTitle: "Conocimiento de la realidad",
    author: "Atribuido tradicionalmente a Śaṅkara",
    date: "Fecha incierta · atribución debatida",
    level: "Exposición clásica",
    purpose: "Introduce cualificaciones, cuerpos, envolturas, estados y vocabulario básico.",
    url: "https://sanskritdocuments.org/doc_z_misc_major_works/tattvabodha.html",
    source: "Sanskrit Documents",
    access: "Texto sánscrito en línea",
    note: "Se conserva la atribución tradicional, sin presentarla como certeza histórica.",
  },
  {
    id: "atma-bodha-essential",
    order: 8,
    title: "Ātma Bodha",
    originalTitle: "Conocimiento del Sí mismo",
    author: "Atribuido tradicionalmente a Śaṅkara",
    date: "Fecha incierta · atribución debatida",
    level: "Exposición clásica",
    purpose: "Presenta mediante imágenes el discernimiento del Sí mismo y la remoción de ignorancia.",
    url: "https://sanskritdocuments.org/doc_z_misc_shankara/aatmabodha.html",
    source: "Sanskrit Documents",
    access: "Texto, transliteración y recursos",
    note: "La autoría de Śaṅkara no se considera históricamente indiscutida.",
  },
  {
    id: "aparokshanubhuti-essential",
    order: 9,
    title: "Aparokṣānubhūti",
    originalTitle: "Realización directa",
    author: "Atribuido tradicionalmente a Śaṅkara",
    date: "Fecha incierta · atribución debatida",
    level: "Manuales de discernimiento",
    purpose: "Desarrolla investigación, desapego, identidad no dual y contemplación.",
    url: "https://sanskritdocuments.org/doc_z_misc_shankara/aparokshaanubhuuti.html",
    source: "Sanskrit Documents",
    access: "Texto sánscrito en línea",
  },
  {
    id: "vivekachudamani-essential",
    order: 10,
    title: "Vivekacūḍāmaṇi",
    originalTitle: "La joya suprema del discernimiento",
    author: "Atribuido tradicionalmente a Śaṅkara",
    date: "Probablemente posterior al siglo VIII · fecha debatida",
    level: "Manuales de discernimiento",
    purpose: "Ordena cualificaciones, maestro, discernimiento, ātman y liberación.",
    url: "https://en.wikisource.org/wiki/Vivekachudamani_%28Swami_Madhavananda%29",
    source: "Wikisource",
    access: "Traducción inglesa de dominio público",
    note: "La atribución a Śaṅkara es tradicional y discutida en la investigación moderna.",
  },
  {
    id: "drg-drsya-essential",
    order: 11,
    title: "Dṛg-Dṛśya-Viveka",
    originalTitle: "Discernimiento entre observador y observado",
    author: "Atribución tradicional discutida",
    date: "ca. siglo XIV · fecha y autoría debatidas",
    level: "Manuales de discernimiento",
    purpose: "Guía la distinción entre conciencia conocedora y todo objeto conocido.",
    url: "https://books.google.com/books/about/Drig_Drisya_Viveka.html?id=5vylDwAAQBAJ",
    source: "Google Books",
    access: "Vista previa legal según región",
  },
  {
    id: "panchadasi-essential",
    order: 12,
    title: "Pañcadaśī",
    author: "Vidyāraṇya",
    date: "ca. siglo XIV",
    level: "Manuales de discernimiento",
    purpose: "Expone en quince capítulos realidad, conciencia, dicha, māyā y liberación.",
    url: "https://sanskritdocuments.org/sites/snsastri/panch-intro.html",
    source: "Sanskrit Documents · S. N. Sastri",
    access: "Introducción y síntesis por capítulos",
  },
  {
    id: "vedantasara-essential",
    order: 13,
    title: "Vedāntasāra",
    originalTitle: "La esencia del Vedanta",
    author: "Sadānanda",
    date: "ca. siglos XV–XVI",
    level: "Profundización y diálogo",
    purpose: "Sintetiza la terminología y la pedagogía del Advaita posclásico.",
    url: "https://sanskritdocuments.org/doc_z_misc_major_works/vedantasara.html",
    source: "Sanskrit Documents",
    access: "Texto sánscrito en línea",
  },
  {
    id: "vedanta-paribhasha-essential",
    order: 14,
    title: "Vedāntaparibhāṣā",
    author: "Dharmarāja Adhvarīndra",
    date: "ca. siglo XVII",
    level: "Profundización y diálogo",
    purpose: "Desarrolla la epistemología del Advaita y sus medios de conocimiento.",
    url: "https://sanskritdocuments.org/doc_z_misc_major_works/paribhasha.html",
    source: "Sanskrit Documents",
    access: "Texto sánscrito en línea",
  },
  {
    id: "advaita-siddhi-essential",
    order: 15,
    title: "Advaitasiddhi",
    author: "Madhusūdana Sarasvatī",
    date: "ca. siglo XVI",
    level: "Profundización y diálogo",
    purpose: "Defiende filosóficamente el Advaita ante objeciones de otras escuelas.",
    url: "https://sanskritdocuments.org/sites/snsastri/Advaitasiddhi-pratikarmavyavasthA.pdf",
    source: "Sanskrit Documents · S. N. Sastri",
    access: "Capítulo seleccionado con traducción inglesa",
    note: "El enlace ofrece una sección autorizada para estudio, no la obra completa.",
  },
  {
    id: "ashtavakra-essential",
    order: 16,
    title: "Aṣṭāvakra Gītā",
    author: "Autor tradicional desconocido",
    date: "ca. siglos VIII–XIV · estimación debatida",
    level: "Profundización y diálogo",
    purpose: "Diálogo radical sobre libertad, conciencia y desapego.",
    url: "https://en.wikisource.org/wiki/Ashtavakra_Gita",
    source: "Wikisource",
    access: "Traducción inglesa de dominio público",
    note: "Se estudia como texto no dual afín; no forma parte del Prasthānatrayī.",
  },
  {
    id: "avadhuta-essential",
    order: 17,
    title: "Avadhūta Gītā",
    author: "Atribuida tradicionalmente a Dattātreya",
    date: "ca. siglos IX–X · estimación aproximada",
    level: "Textos contemplativos y recepción contemporánea",
    purpose: "Canto no dual sobre la libertad indivisible del Ser.",
    url: "https://en.wikisource.org/wiki/Translation%3AAvadhuta_Gita/Chapter_1",
    source: "Wikisource",
    access: "Traducción inglesa de dominio público",
    note: "La atribución a Dattātreya pertenece a la tradición y no es verificable históricamente.",
  },
  {
    id: "yoga-vasistha-essential",
    order: 18,
    title: "Yoga Vāsiṣṭha",
    originalTitle: "Mokṣopāya · tradición textual relacionada",
    author: "Autoría tradicional y composición estratificada",
    date: "ca. siglos X–XIV · formación textual debatida",
    level: "Textos contemplativos y recepción contemporánea",
    purpose: "Despliega relatos e investigaciones sobre mente, apariencia, conciencia y liberación.",
    url: "https://sanskritdocuments.org/doc_yoga/yogavAsiShTha18.html",
    source: "Sanskrit Documents",
    access: "Texto sánscrito en línea",
    note: "Se presenta como obra no dual influyente, no como comentario canónico de Śaṅkara.",
  },
  {
    id: "who-am-i-essential",
    order: 19,
    title: "¿Quién soy yo?",
    originalTitle: "Nāṉ Yār? · Who Am I?",
    author: "Sri Ramana Maharshi",
    date: "Respuestas de 1902 · primera edición tamil de 1923",
    level: "Textos contemplativos y recepción contemporánea",
    purpose: "Puerta moderna a la autoindagación y al examen directo del sentido de yo.",
    url: "https://www.gururamana.org/Resources/Books/Who_Am_I_English.pdf",
    source: "Sri Ramanasramam",
    access: "PDF oficial en inglés",
  },
  {
    id: "i-am-that-essential",
    order: 20,
    title: "Yo soy Eso",
    originalTitle: "I Am That",
    author: "Sri Nisargadatta Maharaj · edición de Maurice Frydman",
    date: "Primera edición inglesa · 1973",
    level: "Textos contemplativos y recepción contemporánea",
    purpose: "Diálogos sobre «yo soy», conciencia, identidad y lo absoluto.",
    url: "https://openlibrary.org/works/OL2971595W/I_Am_That?edition=iamthattalkswith0000nisa",
    source: "Open Library",
    access: "Préstamo digital controlado",
    note: "Obra protegida: Parabrahman enlaza el préstamo y no aloja una copia.",
  },
] as const;

if (advaitaEssentialBooks.length !== 20) {
  throw new Error("El módulo de Vedanta Advaita debe contener exactamente 20 libros fundamentales.");
}
